### ISSUE TITLE
Version 1.3 prevent WooCoomerce emails from being sent

### ISSUE THREAD

**Issue by JohannLesacher** [payplug/payplug-woocommerce#236]
Hello,

I've noticed that if I upgrade to version 1.3 no woocommerce emails are sent to the clients nor the admins.
With version 1.2.11 no such problem.

The error stack I have is this :
```
production.ERROR: Too few arguments to function App\{closure}(), 1 passed in .../public/web/wp/wp-includes/class-wp-hook.php on line 303 and exactly 2 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\{closure}(), 1 passed in .../public/web/wp/wp-includes/class-wp-hook.php on line 303 and exactly 2 expected at .../public/web/app/themes/capillum/app/setup.php:204)
[stacktrace]
#0 .../public/web/wp/wp-includes/class-wp-hook.php(303): App\\{closure}(Object(WC_Email_New_Order))
#1 .../public/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#2 .../public/web/wp/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 .../public/web/app/plugins/woocommerce/templates/emails/admin-new-order.php(58): do_action('woocommerce_ema...', Object(WC_Email_New_Order))
#4 .../public/web/app/plugins/woocommerce/includes/wc-core-functions.php(345): include('/www/woopsbeaut...')
#5 .../public/web/app/plugins/woocommerce/includes/wc-core-functions.php(364): wc_get_template('emails/admin-ne...', Array, '', '')
#6 .../public/web/app/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(133): wc_get_template_html('emails/admin-ne...', Array)
#7 .../public/web/app/plugins/woocommerce/includes/emails/class-wc-email.php(541): WC_Email_New_Order->get_content_html()
#8 .../public/web/app/plugins/woocommerce/includes/emails/class-wc-email-new-order.php(110): WC_Email->get_content()
#9 .../public/web/wp/wp-includes/class-wp-hook.php(303): WC_Email_New_Order->trigger(6456, Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))
#10 .../public/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#11 .../public/web/wp/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#12 .../public/web/app/plugins/woocommerce/includes/class-wc-emails.php(170): do_action_ref_array('woocommerce_ord...', Array)
#13 .../public/web/wp/wp-includes/class-wp-hook.php(303): WC_Emails::send_transactional_email(Array, Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))
#14 .../public/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#15 .../public/web/wp/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#16 .../public/web/app/plugins/woocommerce/includes/class-wc-order.php(373): do_action('woocommerce_ord...', 6456, Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))
#17 .../public/web/app/plugins/woocommerce/includes/class-wc-order.php(222): WC_Order->status_transition()
#18 .../public/web/app/plugins/woocommerce/includes/class-wc-order.php(120): WC_Order->save()
**#19 .../public/web/app/plugins/payplug/src/Gateway/PayplugResponse.php(100): WC_Order->payment_complete('pay_2l3sDwZYTO7...')
#20 .../public/web/app/plugins/payplug/src/Gateway/PayplugIpnResponse.php(74): Payplug\\PayplugWoocommerce\\Gateway\\PayplugResponse->process_payment(Object(Payplug\\Resource\\Payment))
#21 [internal function]: Payplug\\PayplugWoocommerce\\Gateway\\PayplugIpnResponse->process_payment_resource(Object(Payplug\\Resource\\Payment))
#22 .../public/web/app/plugins/payplug/src/Gateway/PayplugIpnResponse.php(50): call_user_func(Array, Object(Payplug\\Resource\\Payment))
#23 .../public/web/wp/wp-includes/class-wp-hook.php(303): Payplug\\PayplugWoocommerce\\Gateway\\PayplugIpnResponse->handle_ipn_response('')**
#24 .../public/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#25 .../public/web/wp/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#26 .../public/web/app/plugins/woocommerce/includes/class-wc-api.php(161): do_action('woocommerce_api...')
#27 .../public/web/wp/wp-includes/class-wp-hook.php(303): WC_API->handle_api_requests(Object(WP))
#28 .../public/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#29 .../public/web/wp/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#30 .../public/web/wp/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#31 .../public/web/wp/wp-includes/class-wp.php(750): WP->parse_request('')
#32 .../public/web/wp/wp-includes/functions.php(1291): WP->main('')
#33 .../public/web/wp/wp-blog-header.php(16): wp()
#34 .../public/web/index.php(6): require('/www/woopsbeaut...')
#35 {main}
```

Have a good day,
Johann

**Comment by dan-payplug** [comment]
Hello @JohannLesacher,

Pourriez-vous prendre contact avec notre support directement [ici](https://support.payplug.com/hc/fr/requests/new) pour préciser le contexte de votre problème afin que notre équipe technique puisse traiter votre demande.

N'hésitez pas à décrire votre parcours traduisant l'anomalie que vous constatez et toute information pertinente.


Merci beaucoup !
