### ISSUE TITLE
Wordpress - error 500

### ISSUE THREAD

**Issue by baptistenoll** [payplug/payplug-woocommerce#807]
Hello, 

I want to use the plugin in a wordpress with woocommerce website.

Versions : 
- WP: 6.4.3
- WooCommerce: 8.6.1
- PayPlug: 2.7.3

When i click the setting button, i got an 500 error with payplug and the settings page of the plugin dont load.
Route: /wp-json/payplug_api/init

Has anybody got and idea ? Thank's !

**Comment by baptistenoll** [comment]
> Hi @baptistenoll do you have you're REST API activated?

Hello, yes, if i go to .../wp-json/, i got a response..

**Comment by PPmmesquita** [comment]
@baptistenoll can you post here your error-log?

**Comment by clementthenard** [comment]
Hi, I've got the exact same problem. I'm using Roots Sage to build my theme and when I activate it, error 500 appears when I want to manage the plugin. On twentyfive theme, everything is OK. 

Here is my stack trace : 

```
[2026-01-02 14:09:49] development.ERROR: Undefined array key "client_data" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"client_data\" at /srv/www/vhosts/clementtd/client.com/public/app/plugins/payplug/src/PayplugWoocommerceHelper.php:742)
[stacktrace]
#0 /srv/www/vhosts/clementtd/client.com/public/app/themes/client/vendor/roots/acorn/src/Roots/Acorn/Bootstrap/HandleExceptions.php(49): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /srv/www/vhosts/clementtd/client.com/public/app/plugins/payplug/src/PayplugWoocommerceHelper.php(742): Roots\\Acorn\\Bootstrap\\HandleExceptions->handleError()
#2 /srv/www/vhosts/clementtd/client.com/public/app/plugins/payplug/src/Admin/Vue.php(79): Payplug\\PayplugWoocommerce\\PayplugWoocommerceHelper::get_live_key()
#3 /srv/www/vhosts/clementtd/client.com/public/app/plugins/payplug/src/Admin/Vue.php(40): Payplug\\PayplugWoocommerce\\Admin\\Vue->payplug_section_logged()
#4 /srv/www/vhosts/clementtd/client.com/public/app/plugins/payplug/src/Admin/Ajax.php(490): Payplug\\PayplugWoocommerce\\Admin\\Vue->init()
#5 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/rest-api/class-wp-rest-server.php(1292): Payplug\\PayplugWoocommerce\\Admin\\Ajax->payplug_init()
#6 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request()
#7 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch()
#8 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/rest-api.php(467): WP_REST_Server->serve_request()
#9 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/class-wp-hook.php(341): rest_api_loaded()
#10 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters()
#11 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/plugin.php(570): WP_Hook->do_action()
#12 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/class-wp.php(418): do_action_ref_array()
#13 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/class-wp.php(821): WP->parse_request()
#14 /srv/www/vhosts/clementtd/client.com/public/wp/wp-includes/functions.php(1343): WP->main()
#15 /srv/www/vhosts/clementtd/client.com/public/wp/wp-blog-header.php(16): wp()
#16 /srv/www/vhosts/clementtd/client.com/public/index.php(7): require('...')
#17 {main}
"} 
``` 

Best regards.
